#!/bin/bash

#SBATCH --partition=gpu_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=ExampleJob
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=00:19:00
#SBATCH --mem=32000M
#SBATCH --output=out_part2_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

# Activate your environment
source activate dl2022
# Run your code
srun python assignment2/part2/clipzs.py --dataset cifar10 --split test
srun python assignment2/part2/clipzs.py --dataset cifar100 --split test